- type: job
  id: ChiefCustodialOfficer
  name: job-name-cco
  description: job-description-cco
  playTimeTracker: JobChiefCustodialOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobInspector
      time: 10800 #3 hrs
      #replaced warden req considering warden now ranked higher
    - !type:RoleTimeRequirement
      role: JobPrisonOfficer
      time: 36000 #10 hrs
    - !type:DepartmentTimeRequirement
      department: SPSecurity
      time: 108000 # 30 hrs
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
  weight: 35
  startingGear: ChiefCustodialOfficerGear
  icon: "JobIconHeadOfSecurity"
  requireAdminNotify: true
  supervisors: job-supervisors-warden
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ChiefCustodialOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol
