- type: job
  id: PrisonOfficer
  name: job-name-prison-officer
  description: job-description-prison-officer
  playTimeTracker: JobPrisonOfficer
  weight: 10
  requirements:
    - !type:DepartmentTimeRequirement
      department: SPSecurity
      time: 36000 #10 hrs
  startingGear: PrisonOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-cco
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: PrisonOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol
