- type: job
  id: MedicalDirector
  name: job-name-md
  description: job-description-md
  playTimeTracker: JobMedicalDirector
  requirements:
    - !type:RoleTimeRequirement
      role: JobSPChemist
      time: 10800 #3 hrs
    - !type:RoleTimeRequirement
      role: JobInfirmaryDoctor
      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: SPMedical
      time: 36000 #10 hrs
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
  weight: 10
  startingGear: MDGear
  icon: "JobIconChiefMedicalOfficer"
  requireAdminNotify: true
  supervisors: job-supervisors-warden
  canBeAntag: false
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: MDGear
  equipment:
    id: CMOPDA
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedicalFilled
  storage:
    back:
    - Flash
