- type: job
  id: Prisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPrisoner
  weight: 25
  startingGear: PrisonerGear
  icon: "JobIconSPPrisoner"
  supervisors: job-supervisors-everyone
  access:
  - Maintenance

- type: startingGear
  id: PrisonerGear
  equipment:
    id: PrisonerPDA
    ears: ClothingHeadsetGrey
  #storage:
    #back:
    #- Stuff
