- type: antag
  id: Liberator
  name: roles-antag-liberator-name
  antagonist: true
  setPreference: true
  objective: roles-antag-liberator-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  guides: [ NuclearOperatives ]

- type: antag
  id: LiberatorMedic
  name: roles-antag-liberator-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-liberator-agent-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  - !type:RoleTimeRequirement
    role: JobSPChemist
    time: 10800 # 3h
  guides: [ NuclearOperatives ]

- type: antag
  id: LiberatorCommander
  name: roles-antag-liberator-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-liberator-commander-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  - !type:DepartmentTimeRequirement
    department: SPSecurity
    time: 36000 # 10h
  # should be changed to nukie playtime when thats tracked (wyci)
  guides: [ NuclearOperatives ]