- type: job
  id: WelfareOfficer
  name: job-name-wo
  description: job-description-wo
  playTimeTracker: JobWelfareOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Maintenance
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: SPMedical
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: SPSecurity
      time: 36000 # 10 hrs
    - !type:DepartmentTimeRequirement
      department: SPCommand
      time: 36000 # 10 hours
  weight: 30
  startingGear: WOGear
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-warden
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  # I mean they'll give themselves the rest of the access levels *anyways*.
  # As of 15/03/23 they can't do that so here's MOST of the rest of the access levels.
  # Head level access that isn't their own was deliberately left out, get AA from the Warden instead.
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: WOGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: HOPDA
    gloves: ClothingHandsGlovesHop
    ears: ClothingHeadsetAltCommand
    belt: BoxFolderClipboard
  storage:
    back:
    - Flash
